spring.application.name=api

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1111

# JDBC driver (optional, auto-detected usually)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

## Okta settings( for Auth0)
#
#okta.oauth2.issuer=https://diploma-project.eu.auth0.com/
#okta.oauth2.client-id=EFshQKP7sSk2T9spVs8jG4B7BF3vg7Ml
#okta.oauth2.client-secret=93xrhbmzdS7l95ah0NLjCO3pqrshGHIoYVXNYfl3Dws6dtV02WCi94WIGB0rDsm6
#okta.oauth2.audience=https://diploma-project.eu.auth0.com/api/v2/
